import type { EquipamentoStatus, EquipamentoTipoControle, EquipamentoVinculo, MovimentacaoEquipamentoTipo } from "./equipamento";
import type { ID } from "./common";
import type { PeriodoCustoEquipamento } from "./custo-equipamento";

export interface PeriodoEstatisticasEquipamentos extends PeriodoCustoEquipamento {}

export interface EstatisticaEquipamentoLinha {
  equipamento_id: ID;
  nome: string;
  modelo: string | null;
  tipo_controle: EquipamentoTipoControle;
  cadastros_fisicos: number;
  quantidade_ativa: number;
  quantidade_saldo: number;
  disponivel: number;
  em_uso: number;
  em_manutencao: number;
  fora_empresa: number;
  encerrados: number;
  dias_com_uso: number;
  dias_em_manutencao: number;
  dias_disponivel: number;
  taxa_utilizacao: number | null;
  entradas: number;
  saidas: number;
  devolucoes: number;
  transferencias: number;
  sinalizacoes_manutencao: number;
  envios_manutencao: number;
  retornos_manutencao: number;
  baixas: number;
  reentradas: number;
  custo_operacional: number;
  custo_manutencao: number;
  custo_recorrente: number;
  custo_total: number;
  quantidade_consumida: number;
  consumos_sem_custo: number;
  manutencoes: number;
  manutencoes_abertas: number;
  manutencoes_concluidas: number;
  duracao_media_manutencao_dias: number | null;
  valor_referencia: number;
  valor_proprio: number;
  valor_alugado: number;
  valor_emprestado: number;
  sem_valor: boolean;
  vinculos: Record<EquipamentoVinculo, number>;
  status: EquipamentoStatus;
}

export interface EstatisticasEquipamentosResumo {
  projeto_id: ID;
  periodo: PeriodoEstatisticasEquipamentos;
  parque_total: number;
  registros_fisicos: number;
  quantidade_ativa: number;
  quantidade_saldo: number;
  disponivel: number;
  em_uso: number;
  em_manutencao: number;
  fora_empresa: number;
  encerrados: number;
  individual: number;
  quantitativo: number;
  proprio: number;
  alugado: number;
  emprestimo: number;
  equipamentos_sem_valor: number;
  dias_com_uso: number;
  dias_em_manutencao: number;
  dias_disponivel: number;
  taxa_utilizacao: number | null;
  entradas: number;
  saidas: number;
  devolucoes: number;
  transferencias: number;
  sinalizacoes_manutencao: number;
  envios_manutencao: number;
  retornos_manutencao: number;
  baixas: number;
  reentradas: number;
  manutencoes: number;
  manutencoes_abertas: number;
  manutencoes_concluidas: number;
  duracao_media_manutencao_dias: number | null;
  quantidade_consumida: number;
  consumos_com_custo: number;
  consumos_sem_custo: number;
  custo_operacional: number;
  custo_manutencao: number;
  custo_recorrente: number;
  custo_total: number;
  valor_referencia: number;
  valor_proprio: number;
  valor_alugado: number;
  valor_emprestado: number;
  movimentacoes: number;
  por_equipamento: EstatisticaEquipamentoLinha[];
  por_tipo_movimentacao: Record<MovimentacaoEquipamentoTipo, number>;
}
