/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApropriacoesRouteImport } from './routes/app.apropriacoes'
import { Route as AppCadastrosRouteImport } from './routes/app.cadastros'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppDadosRouteImport } from './routes/app.dados'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppEquipamentosRouteImport } from './routes/app.equipamentos'
import { Route as AppEstatisticasRouteImport } from './routes/app.estatisticas'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppInventarioRouteImport } from './routes/app.inventario'
import { Route as AppLancarRouteImport } from './routes/app.lancar'
import { Route as AppMovimentacoesRouteImport } from './routes/app.movimentacoes'
import { Route as AppMovimentacoesEquipamentosRouteImport } from './routes/app.movimentacoes-equipamentos'
import { Route as AppProdutoRouteImport } from './routes/app.produto'
import { Route as AppRecebimentosRouteImport } from './routes/app.recebimentos'
import { Route as AppRelatoriosEquipamentosRouteImport } from './routes/app.relatorios-equipamentos'
import { Route as AppVigiaRouteImport } from './routes/app.vigia'
import { Route as AppEstatisticasRelatorioRouteImport } from './routes/app.estatisticas.relatorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApropriacoesRoute = AppApropriacoesRouteImport.update({
  id: '/apropriacoes',
  path: '/apropriacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosRoute = AppCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDadosRoute = AppDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstatisticasRoute = AppEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppLancarRoute = AppLancarRouteImport.update({
  id: '/lancar',
  path: '/lancar',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesRoute = AppMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesEquipamentosRoute =
  AppMovimentacoesEquipamentosRouteImport.update({
    id: '/movimentacoes-equipamentos',
    path: '/movimentacoes-equipamentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppProdutoRoute = AppProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => AppRoute,
} as any)
const AppRecebimentosRoute = AppRecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosEquipamentosRoute =
  AppRelatoriosEquipamentosRouteImport.update({
    id: '/relatorios-equipamentos',
    path: '/relatorios-equipamentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppVigiaRoute = AppVigiaRouteImport.update({
  id: '/vigia',
  path: '/vigia',
  getParentRoute: () => AppRoute,
} as any)
const AppEstatisticasRelatorioRoute =
  AppEstatisticasRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AppEstatisticasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/apropriacoes': typeof AppApropriacoesRoute
  '/app/cadastros': typeof AppCadastrosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dados': typeof AppDadosRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/estatisticas': typeof AppEstatisticasRouteWithChildren
  '/app/estoque': typeof AppEstoqueRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/movimentacoes': typeof AppMovimentacoesRoute
  '/app/movimentacoes-equipamentos': typeof AppMovimentacoesEquipamentosRoute
  '/app/produto': typeof AppProdutoRoute
  '/app/recebimentos': typeof AppRecebimentosRoute
  '/app/relatorios-equipamentos': typeof AppRelatoriosEquipamentosRoute
  '/app/vigia': typeof AppVigiaRoute
  '/app/': typeof AppIndexRoute
  '/app/estatisticas/relatorio': typeof AppEstatisticasRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/apropriacoes': typeof AppApropriacoesRoute
  '/app/cadastros': typeof AppCadastrosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dados': typeof AppDadosRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/estatisticas': typeof AppEstatisticasRouteWithChildren
  '/app/estoque': typeof AppEstoqueRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/movimentacoes': typeof AppMovimentacoesRoute
  '/app/movimentacoes-equipamentos': typeof AppMovimentacoesEquipamentosRoute
  '/app/produto': typeof AppProdutoRoute
  '/app/recebimentos': typeof AppRecebimentosRoute
  '/app/relatorios-equipamentos': typeof AppRelatoriosEquipamentosRoute
  '/app/vigia': typeof AppVigiaRoute
  '/app': typeof AppIndexRoute
  '/app/estatisticas/relatorio': typeof AppEstatisticasRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/apropriacoes': typeof AppApropriacoesRoute
  '/app/cadastros': typeof AppCadastrosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dados': typeof AppDadosRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/estatisticas': typeof AppEstatisticasRouteWithChildren
  '/app/estoque': typeof AppEstoqueRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/movimentacoes': typeof AppMovimentacoesRoute
  '/app/movimentacoes-equipamentos': typeof AppMovimentacoesEquipamentosRoute
  '/app/produto': typeof AppProdutoRoute
  '/app/recebimentos': typeof AppRecebimentosRoute
  '/app/relatorios-equipamentos': typeof AppRelatoriosEquipamentosRoute
  '/app/vigia': typeof AppVigiaRoute
  '/app/': typeof AppIndexRoute
  '/app/estatisticas/relatorio': typeof AppEstatisticasRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/apropriacoes'
    | '/app/cadastros'
    | '/app/configuracoes'
    | '/app/dados'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/estatisticas'
    | '/app/estoque'
    | '/app/inventario'
    | '/app/lancar'
    | '/app/movimentacoes'
    | '/app/movimentacoes-equipamentos'
    | '/app/produto'
    | '/app/recebimentos'
    | '/app/relatorios-equipamentos'
    | '/app/vigia'
    | '/app/'
    | '/app/estatisticas/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/apropriacoes'
    | '/app/cadastros'
    | '/app/configuracoes'
    | '/app/dados'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/estatisticas'
    | '/app/estoque'
    | '/app/inventario'
    | '/app/lancar'
    | '/app/movimentacoes'
    | '/app/movimentacoes-equipamentos'
    | '/app/produto'
    | '/app/recebimentos'
    | '/app/relatorios-equipamentos'
    | '/app/vigia'
    | '/app'
    | '/app/estatisticas/relatorio'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/apropriacoes'
    | '/app/cadastros'
    | '/app/configuracoes'
    | '/app/dados'
    | '/app/documentos'
    | '/app/equipamentos'
    | '/app/estatisticas'
    | '/app/estoque'
    | '/app/inventario'
    | '/app/lancar'
    | '/app/movimentacoes'
    | '/app/movimentacoes-equipamentos'
    | '/app/produto'
    | '/app/recebimentos'
    | '/app/relatorios-equipamentos'
    | '/app/vigia'
    | '/app/'
    | '/app/estatisticas/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apropriacoes': {
      id: '/app/apropriacoes'
      path: '/apropriacoes'
      fullPath: '/app/apropriacoes'
      preLoaderRoute: typeof AppApropriacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros': {
      id: '/app/cadastros'
      path: '/cadastros'
      fullPath: '/app/cadastros'
      preLoaderRoute: typeof AppCadastrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dados': {
      id: '/app/dados'
      path: '/dados'
      fullPath: '/app/dados'
      preLoaderRoute: typeof AppDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos': {
      id: '/app/equipamentos'
      path: '/equipamentos'
      fullPath: '/app/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estatisticas': {
      id: '/app/estatisticas'
      path: '/estatisticas'
      fullPath: '/app/estatisticas'
      preLoaderRoute: typeof AppEstatisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario': {
      id: '/app/inventario'
      path: '/inventario'
      fullPath: '/app/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lancar': {
      id: '/app/lancar'
      path: '/lancar'
      fullPath: '/app/lancar'
      preLoaderRoute: typeof AppLancarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movimentacoes': {
      id: '/app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/app/movimentacoes'
      preLoaderRoute: typeof AppMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movimentacoes-equipamentos': {
      id: '/app/movimentacoes-equipamentos'
      path: '/movimentacoes-equipamentos'
      fullPath: '/app/movimentacoes-equipamentos'
      preLoaderRoute: typeof AppMovimentacoesEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produto': {
      id: '/app/produto'
      path: '/produto'
      fullPath: '/app/produto'
      preLoaderRoute: typeof AppProdutoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recebimentos': {
      id: '/app/recebimentos'
      path: '/recebimentos'
      fullPath: '/app/recebimentos'
      preLoaderRoute: typeof AppRecebimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios-equipamentos': {
      id: '/app/relatorios-equipamentos'
      path: '/relatorios-equipamentos'
      fullPath: '/app/relatorios-equipamentos'
      preLoaderRoute: typeof AppRelatoriosEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vigia': {
      id: '/app/vigia'
      path: '/vigia'
      fullPath: '/app/vigia'
      preLoaderRoute: typeof AppVigiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estatisticas/relatorio': {
      id: '/app/estatisticas/relatorio'
      path: '/relatorio'
      fullPath: '/app/estatisticas/relatorio'
      preLoaderRoute: typeof AppEstatisticasRelatorioRouteImport
      parentRoute: typeof AppEstatisticasRoute
    }
  }
}

interface AppEstatisticasRouteChildren {
  AppEstatisticasRelatorioRoute: typeof AppEstatisticasRelatorioRoute
}

const AppEstatisticasRouteChildren: AppEstatisticasRouteChildren = {
  AppEstatisticasRelatorioRoute: AppEstatisticasRelatorioRoute,
}

const AppEstatisticasRouteWithChildren = AppEstatisticasRoute._addFileChildren(
  AppEstatisticasRouteChildren,
)

interface AppRouteChildren {
  AppApropriacoesRoute: typeof AppApropriacoesRoute
  AppCadastrosRoute: typeof AppCadastrosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDadosRoute: typeof AppDadosRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppEstatisticasRoute: typeof AppEstatisticasRouteWithChildren
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppLancarRoute: typeof AppLancarRoute
  AppMovimentacoesRoute: typeof AppMovimentacoesRoute
  AppMovimentacoesEquipamentosRoute: typeof AppMovimentacoesEquipamentosRoute
  AppProdutoRoute: typeof AppProdutoRoute
  AppRecebimentosRoute: typeof AppRecebimentosRoute
  AppRelatoriosEquipamentosRoute: typeof AppRelatoriosEquipamentosRoute
  AppVigiaRoute: typeof AppVigiaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApropriacoesRoute: AppApropriacoesRoute,
  AppCadastrosRoute: AppCadastrosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDadosRoute: AppDadosRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppEstatisticasRoute: AppEstatisticasRouteWithChildren,
  AppEstoqueRoute: AppEstoqueRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppLancarRoute: AppLancarRoute,
  AppMovimentacoesRoute: AppMovimentacoesRoute,
  AppMovimentacoesEquipamentosRoute: AppMovimentacoesEquipamentosRoute,
  AppProdutoRoute: AppProdutoRoute,
  AppRecebimentosRoute: AppRecebimentosRoute,
  AppRelatoriosEquipamentosRoute: AppRelatoriosEquipamentosRoute,
  AppVigiaRoute: AppVigiaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
